export const SUCCESS_MESSAGE = {
  IMAGE_DELETED: "Image deleted successfully",
  FILE_DELETED: "File deleted successfully",
  FILE_UPLOADED: "File uploaded Successfully",
  DOCUMENTS_FETCHED: "Documents fetched Successfully",
  PROFILES_FETCHED: "Profile pictures fetched Successfully",
  ENUMS_FETCHED: "Enums fetched successfully",
  REGISTER_USER: "Successfully registered user",
  LOGIN_USER_CONTROLLER: "Successfully logged in",
  RESET_PASSWORD: "Successfully reset password.",
  LOGOUT_USER: "Logged Out Successfully",
  CREATE_DATA: "MyData created successfully",
  FETCH_DATA: "Successfully fetched MyData",
  UPDATE_DATA: "Successfully updated MyData",
  DELETE_DATA: "Successfully deleted MyData",
  FETCH_USER: "Successfully fetched users",
  UPDATE_USER: "Successfully updated user",
  DELETE_USER: "Successfully deleted user",
  UPDATE_PASSWORD: "Password updated successfully",
  FILE_UPLOAD: "ProfilePic uploaded successfully",
  SUBJECT: "Password Reset",
  DEFAULT_PASS: "2WQgXqaj",
  MYDATA_SUBJECT: "Internal-App credentials",
  CREDENTIAL_EMAIL: "Login credentials are sent to your email",
  DROPDOWN_CREATED: "Dropdown created Successfully",
  DROPDOWN_UPDATED: "Dropdown updated Successfully",
  DROPDOWN_DELETED: "Dropdown deleted",
  CONSENT_SENT: "Consent sent successfully",
  CONSENT_FETCHED: "Consent fetched successfully",
  RESET_PASSWORD_SENT: "New password sent successfully",
  PROJECT_CREATED: "Project created successfully",
  PROJECTS_RETRIEVED: "Projects fetched successfully",
  PROJECT_RETRIEVED: "Project fetched successfully",
  PROJECT_DELETED: "Project deleted successfully",
  EMPLOYEE_ASSIGNED: "employee successfully assigned to project",
  EMPLOYEE_REMOVED: "employee successfully removed from project",
  TASK_CREATED: "Task created successfully",
  TASKS_RETRIEVED: "Tasks retrieved successfully",
  TASK_RETRIEVED: "Task retrieved successfully",
  TASK_UPDATED: "Task updated successfully",
  TASK_DELETED: "Task deleted successfully",
  ACTIVITY_LOG_CREATED: "Activity log created successfully",
  ACTIVITY_LOGS_RETRIEVED: "Activity logs retrieved successfully",
  ACTIVITY_LOGS_RETRIEVED_BY_USER:
    "Activity logs retrieved by user successfully",
  ACTIVITY_LOGS_RETRIEVED_BY_TYPE:
    "Activity logs retrieved by type successfully",
  ACTIVITY_LOG_DELETED: "Activity log deleted successfully",
  ACTIVITY_LOG_UPDATED: "Activity log updated successfully",
};
